# Generated by Django 5.0.4 on 2024-04-25 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_dadasabertas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadasAbertas',
            new_name='DatasAbertas',
        ),
    ]
